spring:
  application:
    name: ch7-2-eureka-server
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
