spring:
  cloud:
    gateway:
      routes:
        - id: baidu_route
          uri: http://baidu.com:80/
          predicates:
            - Path=/baidu
  application:
    name: spring-cloud-gateway
server:
  port: 8081
logging: ## Spring Cloud Gateway的日志配置
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
