spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/gexiantao/config.git
          search-paths: ch11-1-config/**
  application:
    name: ch11-1-config-git
server:
  port: 9090