spring:
  application:
    name: zuul-server
server:
  port: 5555
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    client-a:
      path: /client/**
      serviceId: client-a
security:
  oauth2:
    client:
      access-token-uri: http://localhost:7777/uaa/oauth/token
      user-authorization-uri: http://localhost:7777/uaa/oauth/authorize
    resource:
      jwt:
        key-value: springcloud123
