server:
  port: 8098
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
turbine:
  appConfig: ch6-3-hello,ch6-3-hello-provider
  clusterNameExpression: "'default'"